### ISSUE TITLE
Unhandled Exception: Unsupporter field attribute

### ISSUE THREAD

**Issue by Tajnymag** [IBM/prisma-schema-transformer#3]
Given this schema:

```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model addresses {
  city_name     String
  id            Int           @default(autoincrement()) @id
  street_name   String
  street_number String
  zip           String
  biographies   biographies[]
}

model biographies {
  address_id Int?
  email      String?
  full_name  String
  id         Int        @default(autoincrement()) @id
  addresses  addresses? @relation(fields: [address_id], references: [id])
  users      users[]
}

model company_settings {
  id      Int    @id
  locale  String @default("en")
  logo_id Int
  name    String
  files   files  @relation(fields: [logo_id], references: [id])
}

model contract_assignees {
  contract_id Int
  user_id     Int

  @@id([user_id, contract_id])
}

model contracts {
  code                                       String
  id                                         Int    @default(autoincrement()) @id
  made_by_id                                 Int
  responsible_user_id                        Int
  users_contracts_made_by_idTousers          users  @relation("contracts_made_by_idTousers", fields: [made_by_id], references: [id])
  users_contracts_responsible_user_idTousers users  @relation("contracts_responsible_user_idTousers", fields: [responsible_user_id], references: [id])
}

model files {
  hash             String
  id               Int                @default(autoincrement()) @id
  name             String
  uploaded_by_id   Int
  users            users              @relation(fields: [uploaded_by_id], references: [id])
  company_settings company_settings[]
}

model preferences {
  id               Int     @default(autoincrement()) @id
  preferred_locale String  @default("en")
  users            users[]
}

model users {
  biography_id                                   Int
  id                                             Int         @default(autoincrement()) @id
  password_hash                                  String
  preferences_id                                 Int
  username                                       String
  biographies                                    biographies @relation(fields: [biography_id], references: [id])
  preferences                                    preferences @relation(fields: [preferences_id], references: [id])
  contracts_contracts_made_by_idTousers          contracts[] @relation("contracts_made_by_idTousers")
  contracts_contracts_responsible_user_idTousers contracts[] @relation("contracts_responsible_user_idTousers")
  files                                          files[]
}
```

I get this process output when trying to do anything with the above schema:

```
(node:18084) UnhandledPromiseRejectionWarning: Error: Unsupporter field attribute en
    at Object.default (REDACTED_PATH_TO_REPO\node_modules\prisma-schema-transformer\dist\deserializer.js:19:19)
    at REDACTED_PATH_TO_REPO\node_modules\prisma-schema-transformer\dist\deserializer.js:39:75
    at Array.map (<anonymous>)
    at handleAttributes (REDACTED_PATH_TO_REPO\node_modules\prisma-schema-transformer\dist\deserializer.js:39:43)
    at REDACTED_PATH_TO_REPO\node_modules\prisma-schema-transformer\dist\deserializer.js:53:65
    at Array.map (<anonymous>)
    at handleFields (REDACTED_PATH_TO_REPO\node_modules\prisma-schema-transformer\dist\deserializer.js:50:10)
    at deserializeModel (REDACTED_PATH_TO_REPO\node_modules\prisma-schema-transformer\dist\deserializer.js:72:3)
    at REDACTED_PATH_TO_REPO\node_modules\prisma-schema-transformer\dist\deserializer.js:82:32
    at Array.map (<anonymous>)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:18084) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled
-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:18084) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.
Done in 1.05s.
```

It seems the transformer fails on handling of default string values of columns.

**Comment by ExiaSR** [comment]
Fixed in https://github.com/IBM/prisma-schema-transformer/compare/v0.2.2...v0.3.0
